### ISSUE TITLE
ko.toJSON

### ISSUE THREAD

**Issue by cslarson** [jimrhoskins/knockout.localStorage#1]
Hi, I made the following change (line 26) when using your knockout plugin (knockout.localStorage) which resulted in observables that were not persisting to do so. Not sure if there might be other problems associated with doing this. Thanks!

``` javascript
...
localStorage.setItem(key, JSON.stringify(newValue));
```

``` javascript
...
localStorage.setItem(key, ko.toJSON(newValue));
```

**Comment by jimrhoskins** [comment]
Thanks for the fix. It doesn't look like this should adversely affect anything else.
